- name: Restart unattended-upgrades
  service:
    name: unattended-upgrades
    state: restarted
  ignore_errors: "{{ ansible_check_mode }}"

- name: Restart vault
  service:
    name: vault
    state: restarted
    enabled: yes
  ignore_errors: "{{ ansible_check_mode }}"

- name: Reload systemd
  systemd:
    daemon_reload: yes
  ignore_errors: "{{ ansible_check_mode }}"
