- name: Install required packages
  apt:
    name:
      - sudo
      - unattended-upgrades
      - apt-listchanges
      - wget
      - gpg
    state: present
    update_cache: yes

- name: Add HashiCorp GPG key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg
    state: present
  ignore_errors: "{{ ansible_check_mode }}"

- name: Add HashiCorp repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com bookworm main"
    filename: hashicorp
    state: present
    update_cache: yes

- name: Install HashiCorp Vault
  apt:
    name: vault
    state: present
  ignore_errors: "{{ ansible_check_mode }}"

- name: Create Vault configuration directory
  file:
    path: /etc/vault.d
    state: directory
    owner: vault
    group: vault
    mode: '0755'

- name: Create Vault configuration file
  template:
    src: vault.hcl.j2
    dest: /etc/vault.d/vault.hcl
    owner: vault
    group: vault
    mode: '0640'
  notify: Restart vault

- name: Create Google credentials file for Vault
  copy:
    dest: /etc/vault.d/vault_service_account_key.json
    content: "{{ vault_service_account_key }}"
    owner: vault
    group: vault
    mode: '0600'
  no_log: true

- name: Copy 50unattended-upgrades file
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: '0644'
  notify: Restart unattended-upgrades
