- name: Install required packages
  apt:
    name:
      - sudo
      - unattended-upgrades
      - apt-listchanges
      - bind9
    state: present
    update_cache: yes

- name: Prepare zone files directory
  file:
    path: /etc/bind/zones
    state: directory
    owner: root
    group: bind
    mode: '0755'

- name: Copy named.conf.local
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: root
    group: root
    mode: '0644'
  notify: Restart Bind9

- name: Copy zone file
  template:
    src: db.home.batko.me.j2
    dest: /etc/bind/zones/db.home.batko.me
    owner: root
    group: bind
    mode: '0644'
  notify: Restart Bind9
