- name: Restart bind9
  service:
    name: bind9
    state: restarted
  ignore_errors: "{{ ansible_check_mode }}"

- name: Restart unattended-upgrades
  service:
    name: unattended-upgrades
    state: restarted
  ignore_errors: "{{ ansible_check_mode }}"
