- name: Install required packages
  apt:
    name:
      - sudo
      - unattended-upgrades
      - apt-listchanges
      - curl
      - unzip
      - git
      - software-properties-common
      - gnupg
      - terraform
      - ansible
      - nodejs
      - npm
      - certbot
      - python3-certbot-dns-cloudflare
    state: present
    update_cache: yes

- name: Copy 50unattended-upgrades file
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: '0644'
  notify: Restart unattended-upgrades
