name: Deploy

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: read

jobs:
  deploy-terraform:
    if: github.event.pull_request.merged == true
    name: Deploy Terraform Changes
    runs-on: self-hosted
    environment: homelab
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      PROXMOX_VE_API_TOKEN: ${{ secrets.PROXMOX_VE_API_TOKEN }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ vars.TERRAFORM_VERSION }}

    - name: Initialize Terraform
      run: terraform init
      working-directory: ./terraform

    - name: Apply Terraform Plan
      run: terraform apply -auto-approve
      working-directory: ./terraform

  deploy-ansible:
    if: github.event.pull_request.merged == true
    name: Deploy Ansible Changes
    runs-on: self-hosted
    environment: homelab
    needs: deploy-terraform

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Prepare SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./id_ed25519
        chmod 600 ./id_ed25519
      working-directory: ./ansible

    - name: Run Ansible Playbooks
      run: ansible-playbook -i inventory/hosts.yml site.yml --diff --private-key ./id_ed25519
      working-directory: ./ansible
