name: Deploy

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: read

jobs:
  deploy-terraform:
    if: github.event.pull_request.merged == true
    name: Deploy Changes
    runs-on: self-hosted
    environment: homelab
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      PROXMOX_VE_API_TOKEN: ${{ secrets.PROXMOX_VE_API_TOKEN }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ vars.TERRAFORM_VERSION }}

    - name: Initialize Terraform
      run: terraform init -backend=false
      working-directory: ./terraform

    - name: Apply Terraform Plan
      run: terraform apply -auto-approve
      working-directory: ./terraform
