name: Deploy

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: read
  id-token: write

jobs:
  deploy-terraform:
    if: github.event.pull_request.merged == true
    name: Deploy Terraform Changes
    runs-on: self-hosted
    environment: homelab
    timeout-minutes: 5
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      PROXMOX_VE_API_TOKEN: ${{ secrets.PROXMOX_VE_API_TOKEN }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v3 
      with:
        workload_identity_provider: ${{ vars.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ vars.GOOGLE_SERVICE_ACCOUNT }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ vars.TERRAFORM_VERSION }}

    - name: Initialize Terraform
      run: terraform init
      working-directory: ./terraform

    - name: Apply Terraform Plan
      run: terraform apply -auto-approve
      working-directory: ./terraform

  deploy-ansible:
    if: github.event.pull_request.merged == true
    name: Deploy Ansible Changes
    runs-on: self-hosted
    environment: homelab
    timeout-minutes: 5
    needs: deploy-terraform

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Run Ansible Playbooks
      run: |
        eval "$(ssh-agent -s)"
        echo "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}" | ssh-add -
        ansible-playbook site.yml --diff \
          -e actions_access_token="${{ secrets.ACTIONS_ACCESS_TOKEN }}" \
          -e ansible_ssh_private_key="$(echo '${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}' | base64 -w 0)" \
          -e cloudflare_api_token="${{ secrets.CLOUDFLARE_API_TOKEN }}" \
          -e proxmox_api_token="${{ secrets.PROXMOX_VE_API_TOKEN }}" \
          -e vault_service_account_key="$(echo '${{ secrets.VAULT_SERVICE_ACCOUNT_KEY }}' | base64 -w 0)"
      working-directory: ./ansible
