name: Deploy

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy-terraform:
    name: Deploy Changes
    runs-on: self-hosted
    environment: homelab
    if: github.event.pull_request.merged == true

    strategy:
      matrix:
        directory:
          - proxmox
          - cloudflare
          # Add more directories for additional Terraform providers as needed

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ vars.TERRAFORM_VERSION }}

    - name: Initialize Terraform
      run: terraform init -backend=false
      working-directory: terraform/${{ matrix.directory }}

    - name: Apply Terraform Plan
      run: terraform apply -auto-approve
      working-directory: terraform/${{ matrix.directory }}