name: Terraform Plan

on:
  push:
    branches:
      - "**"

jobs:
  terraform:
    name: Terraform Plan
    runs-on: self-hosted

    strategy:
      matrix:
        folder:
          - terraform/proxmox
          - terraform/cloudflare
          # Add more directories for additional providers as needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ matrix.folder }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ matrix.folder }}

      - name: Terraform Plan
        run: terraform plan -no-color
        working-directory: ${{ matrix.folder }}
